# Travis CI configuration
language: node_js
node_js:
  - "node" # latest stable Node.js release
cache: npm
script:
  - vue-cli-service build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
